name = "lnapages"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "LNAPAGES_DB"
database_name = "lnapages"
database_id = "f6f4f30a-ec78-4f76-98a4-9f51445afe73"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "LNAPAGES_GALLERY"
bucket_name = "lnapages-gallery"

[[kv_namespaces]]
binding = "LNAPAGES_CONFIG"
id = "e776936711fe4c91a9e31a89534732de"

[vars]
APP_URL = ""
R2_PUBLIC_BASE_URL = ""
GITHUB_REPO_OWNER = "LnAPages"
