-- 0015_gallery_crop_and_misc.sql
-- Issue #50 Part B + wishlist remainder: non-destructive gallery crops,
-- focal points, per-context overrides, derived renditions, video sources,
-- location/maps blocks, gallery display modes.

-- Extend gallery_items with focal point + media kind polish.
ALTER TABLE gallery_items ADD COLUMN focal_x REAL;
ALTER TABLE gallery_items ADD COLUMN focal_y REAL;
ALTER TABLE gallery_items ADD COLUMN dominant_color TEXT;
ALTER TABLE gallery_items ADD COLUMN duration_seconds REAL;
ALTER TABLE gallery_items ADD COLUMN drive_folder TEXT;

-- Crops are non-destructive: original r2_key is never destroyed.
-- One gallery_item can have many crops (hero 16:9, card 1:1, grid 4:5, etc.).
CREATE TABLE IF NOT EXISTS gallery_crops (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    gallery_item_id INTEGER NOT NULL,
    context_key TEXT NOT NULL,
    aspect TEXT NOT NULL,
    crop_x REAL NOT NULL,
    crop_y REAL NOT NULL,
    crop_width REAL NOT NULL,
    crop_height REAL NOT NULL,
    rotation INTEGER NOT NULL DEFAULT 0,
    flip_h INTEGER NOT NULL DEFAULT 0,
    flip_v INTEGER NOT NULL DEFAULT 0,
    output_r2_key TEXT,
    output_width INTEGER,
    output_height INTEGER,
    output_format TEXT,
    created_by INTEGER,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(gallery_item_id, context_key),
    FOREIGN KEY (gallery_item_id) REFERENCES gallery_items(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES admin_users(id)
  );
CREATE INDEX IF NOT EXISTS idx_gallery_crops_item ON gallery_crops(gallery_item_id);
CREATE INDEX IF NOT EXISTS idx_gallery_crops_context ON gallery_crops(context_key);

-- Derived renditions (WebP/AVIF at various widths). Auto-generated by image
-- worker. Cached in R2 at output_r2_key.
CREATE TABLE IF NOT EXISTS gallery_renditions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    gallery_item_id INTEGER NOT NULL,
    crop_id INTEGER,
    format TEXT NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    r2_key TEXT NOT NULL,
    size_bytes INTEGER,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (gallery_item_id) REFERENCES gallery_items(id) ON DELETE CASCADE,
    FOREIGN KEY (crop_id) REFERENCES gallery_crops(id) ON DELETE CASCADE
  );
CREATE INDEX IF NOT EXISTS idx_gallery_renditions_item ON gallery_renditions(gallery_item_id);
CREATE INDEX IF NOT EXISTS idx_gallery_renditions_crop ON gallery_renditions(crop_id);

-- Drive folder registry: lets owner add additional Drive folders (videos, etc.)
-- beyond the single folder currently hard-coded.
CREATE TABLE IF NOT EXISTS drive_folders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    label TEXT NOT NULL,
    drive_folder_id TEXT NOT NULL UNIQUE,
    media_kind TEXT NOT NULL DEFAULT 'image',
    default_category TEXT,
    sync_enabled INTEGER NOT NULL DEFAULT 1,
    last_synced_at TEXT,
    last_sync_status TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  );
CREATE INDEX IF NOT EXISTS idx_drive_folders_kind ON drive_folders(media_kind);

-- Gallery display modes per category (grid, masonry, tinder swipe, carousel).
CREATE TABLE IF NOT EXISTS gallery_display_modes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    category TEXT NOT NULL UNIQUE,
    display_mode TEXT NOT NULL DEFAULT 'grid',
    config_json TEXT NOT NULL DEFAULT '{}',
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

-- Location / map blocks (hyperlinked directions + optional snapshot image).
CREATE TABLE IF NOT EXISTS location_blocks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    slug TEXT NOT NULL UNIQUE,
    label TEXT NOT NULL,
    address_line1 TEXT,
    address_line2 TEXT,
    city TEXT,
    region TEXT,
    postal TEXT,
    country TEXT,
    lat REAL,
    lng REAL,
    directions_url TEXT,
    map_snapshot_r2_key TEXT,
    notes TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  );
CREATE INDEX IF NOT EXISTS idx_location_blocks_active ON location_blocks(active, sort_order);

-- Service category -> tag auto-spawn mapping (wishlist: auto-tag photos by service).
CREATE TABLE IF NOT EXISTS service_auto_tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    service_category TEXT NOT NULL,
    tag_slug TEXT NOT NULL,
    UNIQUE(service_category, tag_slug)
  );

-- Seed the default display modes and carousel contexts.
INSERT OR IGNORE INTO gallery_display_modes (category, display_mode, config_json) VALUES
  ('all', 'grid', '{"columns":3}'),
  ('film', 'masonry', '{"columns":3}'),
  ('photo', 'grid', '{"columns":4}'),
  ('design', 'tinder', '{"stack":3}');
